---
# Title: role-postfix-relay-server
#
# Author: bitfinity-nl
# File: defaults/main.yml
#
# Description:
#   Send mail via 587 or 465
#

- name: "Generate certificate"
  import_tasks: ubt-1804-amd64.yml
  when:
    - ansible_distribution_version == "18.04"
    - ansible_architecture == "x86_64"