---
# Title: role-postfix-relay-server
#
# Author: Bitfinity-nl / L. Rutten
# File: defaults/main.yml
#
# Description:
#   This task file contains the tasks to install and
#   configure a postfix relay server. Mails can be
#   send mail via port 587/tcp or 465/tcp.
#
# Testing:
#   testsaslauthd -u administrator -p <password>
#

- name: "Tasks for Ubuntu 18.04LTS AMD64"
  import_tasks: ubt-1804-amd64.yml
  when:
    - ansible_distribution_version == "18.04"
    - ansible_architecture == "x86_64"

- name: "Tasks for Ubuntu 20.04LTS AMD64"
  import_tasks: ubt-2004-amd64.yml
  when:
    - ansible_distribution_version == "20.04"
    - ansible_architecture == "x86_64"

- name: "Tasks for Ubuntu 22.04LTS AMD64"
  import_tasks: ubt-2204-amd64.yml
  when:
    - ansible_distribution_version == "22.04"
    - ansible_architecture == "x86_64"
