---
# Title: role-postfix-relay-server
#
# Author: bitfinity-nl
# File: defaults/main.yml
#
# Description:
#   Send mail via 587 or 465

- name: "restart_saslauthd"
  systemd:
    name: saslauthd
    state: restarted

- name: "restart_postfix"
  systemd:
    name: postfix
    state: restarted