---

- name: "block Firewall for certbot on port 80/tcp and 443/tcp"
  community.general.ufw:
    rule: deny
    name: Apache Full

- name: "Allow Firewall for OpenSSH on port 22/tcp"
  community.general.ufw:
    state: enabled
    rule: limit
    name: OpenSSH

- name: "Allow Firewall for Postix"
  community.general.ufw:
    state: enabled
    rule: allow
    name: "{{ item }}"
  loop:
    - Postfix
    - Postfix SMTPS
    - Postfix Submission

- name: "Transfer sshs.conf.j2 to /etc/fail2ban/jail.d/sshd.conf"
  ansible.builtin.template:
    src: templates/fail2ban/postfix.conf.j2
    dest: /etc/fail2ban/jail.d/postfix.conf
  notify:
    - fail2ban_restart
       
